In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import skew
import seaborn as sns

In [96]:
df = pd.read_csv("pricing.csv")

In [97]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [98]:
for j in df:
    print(j)
    print(df[j].isna().sum())

Id
0
MSSubClass
0
MSZoning
0
LotFrontage
259
LotArea
0
Street
0
Alley
1369
LotShape
0
LandContour
0
Utilities
0
LotConfig
0
LandSlope
0
Neighborhood
0
Condition1
0
Condition2
0
BldgType
0
HouseStyle
0
OverallQual
0
OverallCond
0
YearBuilt
0
YearRemodAdd
0
RoofStyle
0
RoofMatl
0
Exterior1st
0
Exterior2nd
0
MasVnrType
872
MasVnrArea
8
ExterQual
0
ExterCond
0
Foundation
0
BsmtQual
37
BsmtCond
37
BsmtExposure
38
BsmtFinType1
37
BsmtFinSF1
0
BsmtFinType2
38
BsmtFinSF2
0
BsmtUnfSF
0
TotalBsmtSF
0
Heating
0
HeatingQC
0
CentralAir
0
Electrical
1
1stFlrSF
0
2ndFlrSF
0
LowQualFinSF
0
GrLivArea
0
BsmtFullBath
0
BsmtHalfBath
0
FullBath
0
HalfBath
0
BedroomAbvGr
0
KitchenAbvGr
0
KitchenQual
0
TotRmsAbvGrd
0
Functional
0
Fireplaces
0
FireplaceQu
690
GarageType
81
GarageYrBlt
81
GarageFinish
81
GarageCars
0
GarageArea
0
GarageQual
81
GarageCond
81
PavedDrive
0
WoodDeckSF
0
OpenPorchSF
0
EnclosedPorch
0
3SsnPorch
0
ScreenPorch
0
PoolArea
0
PoolQC
1453
Fence
1179
MiscFeature
1406
MiscVal
0
MoSold
0
YrSold
0
SaleType
0
SaleCondition
0
SalePrice
0

In [72]:
sns.heatmap(df.corr())
plt.show()

ValueError: could not convert string to float: 'RL'

In [99]:
len(df)

1460

In [100]:
df["Alley"].isna().sum()

1369

In [101]:
df.Alley = df.Alley.fillna(0)

In [102]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,0,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,0,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,0,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,0,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,0,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [103]:
df.LotFrontage.isna().sum()

259

In [104]:
df.LotFrontage = df.LotFrontage.fillna(int(9999))

In [105]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,0,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,0,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,0,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,0,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,0,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,0,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [106]:
df.PoolQC.isna().sum()

1453

In [107]:
df = df.drop("PoolQC", axis = 1)

In [108]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,0,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,0,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,0,IR1,Lvl,AllPub,...,0,0,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,0,IR1,Lvl,AllPub,...,0,0,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,0,IR1,Lvl,AllPub,...,0,0,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,0,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,0,Reg,Lvl,AllPub,...,0,0,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,0,Reg,Lvl,AllPub,...,0,0,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,0,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,0,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,6,2008,WD,Normal,147500

In [109]:
df.Fence.head(50)

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5     MnPrv
6       NaN
7       NaN
8       NaN
9       NaN
10      NaN
11      NaN
12      NaN
13      NaN
14     GdWo
15    GdPrv
16      NaN
17      NaN
18      NaN
19    MnPrv
20      NaN
21    GdPrv
22      NaN
23      NaN
24    MnPrv
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
30    MnPrv
31    MnPrv
32      NaN
33      NaN
34      NaN
35      NaN
36      NaN
37      NaN
38      NaN
39      NaN
40     GdWo
41      NaN
42    MnPrv
43    MnPrv
44      NaN
45      NaN
46      NaN
47      NaN
48      NaN
49    MnPrv
Name: Fence, dtype: object

In [110]:
df.Fence = df.Fence.fillna("9999")

In [111]:
for j in df:
    print(j)
    print(df[j].isna().sum())

Id
0
MSSubClass
0
MSZoning
0
LotFrontage
0
LotArea
0
Street
0
Alley
0
LotShape
0
LandContour
0
Utilities
0
LotConfig
0
LandSlope
0
Neighborhood
0
Condition1
0
Condition2
0
BldgType
0
HouseStyle
0
OverallQual
0
OverallCond
0
YearBuilt
0
YearRemodAdd
0
RoofStyle
0
RoofMatl
0
Exterior1st
0
Exterior2nd
0
MasVnrType
872
MasVnrArea
8
ExterQual
0
ExterCond
0
Foundation
0
BsmtQual
37
BsmtCond
37
BsmtExposure
38
BsmtFinType1
37
BsmtFinSF1
0
BsmtFinType2
38
BsmtFinSF2
0
BsmtUnfSF
0
TotalBsmtSF
0
Heating
0
HeatingQC
0
CentralAir
0
Electrical
1
1stFlrSF
0
2ndFlrSF
0
LowQualFinSF
0
GrLivArea
0
BsmtFullBath
0
BsmtHalfBath
0
FullBath
0
HalfBath
0
BedroomAbvGr
0
KitchenAbvGr
0
KitchenQual
0
TotRmsAbvGrd
0
Functional
0
Fireplaces
0
FireplaceQu
690
GarageType
81
GarageYrBlt
81
GarageFinish
81
GarageCars
0
GarageArea
0
GarageQual
81
GarageCond
81
PavedDrive
0
WoodDeckSF
0
OpenPorchSF
0
EnclosedPorch
0
3SsnPorch
0
ScreenPorch
0
PoolArea
0
Fence
0
MiscFeature
1406
MiscVal
0
MoSold
0
YrSold
0
SaleType
0
SaleCondition
0
SalePrice
0

In [112]:
for j in df:
    if df[j].isna().sum() <= 81:
        df[j] = df[j].fillna(int(9999))

In [113]:
df.MasVnrType.isna().sum()

872

In [114]:
df.MasVnrType

0       BrkFace
1           NaN
2       BrkFace
3           NaN
4       BrkFace
         ...
1455        NaN
1456      Stone
1457        NaN
1458        NaN
1459        NaN
Name: MasVnrType, Length: 1460, dtype: object

In [115]:
df.MasVnrType = df.MasVnrType.fillna(int(0))

In [116]:
df.MiscFeature = df.MiscFeature.fillna(0)

In [117]:
df.FireplaceQu.mode()

0    Gd
Name: FireplaceQu, dtype: object

In [118]:
df.FireplaceQu = df.FireplaceQu.fillna(0000)
sambanda- s g- rm = constitutional position increasing in sambanda relation knowing
abhideya- r g- rg =   (rules and regulation and ettiquetes for bhakthi and actions) 
prayojana- rdg - rgopinath = results (to get krsna prem)